version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hooshpod-landing-web
    environment:
      - NODE_ENV=production
      - PORT=3000
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
      - ./certbot-data:/data/letsencrypt
    networks:
      - app_network

volumes:
  certbot-etc:
  certbot-webroot:
